//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int id { get; set; }
        public string KullaniciAdi { get; set; }
        public string Parola { get; set; }
        public Nullable<int> ResimID { get; set; }
        public string aciklama { get; set; }
        public string baslik { get; set; }
    
        public virtual Resim Resim { get; set; }
    }
}
