//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesaj
    {
        public int id { get; set; }
        public string gonderenMail { get; set; }
        public string gonderenAdi { get; set; }
        public string mesaj1 { get; set; }
        public System.DateTime tarih { get; set; }
    }
}
