//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int id { get; set; }
        public string YorumYapanAdi { get; set; }
        public System.DateTime Tarih { get; set; }
        public string YorumIcerik { get; set; }
        public int MakaleID { get; set; }
        public string YorumYapanMail { get; set; }
    
        public virtual Makale Makale { get; set; }
    }
}
